name: flutter_core
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  #fire_base:
  firebase_messaging: ^14.9.2
  firebase_core: ^2.31.0
  #localstore:
  shared_preferences: ^2.2.3

  #responsive
  flutter_screenutil: ^5.9.0

  #image
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1

  #status internet
  connectivity_plus: ^6.0.3

  #extension
  copy_with_extension: ^5.0.4
  logger: ^2.2.0
  get_it: ^7.7.0
  injectable: ^2.4.1
  freezed_annotation: ^2.4.1

  #preview devicce
  device_preview: ^1.1.0

  #localozaion language
  easy_localization: ^3.0.6

  #bloc
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5

  #notifications
  flutter_local_notifications: ^17.1.2

  #splash & icon app
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

  #network
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  json_annotation: ^4.9.0


  #cache network
#  dio_http_cache_lts: ^0.4.1

  #route
  auto_route: ^7.0.0

  #widget
  shimmer: ^3.0.0

  #env
  flutter_dotenv: ^5.1.0

  # 3th lib
  top_snackbar_flutter: ^3.1.0
  dartz: ^0.10.1
  infinite_scroll_pagination: ^4.0.0
  photo_view: ^0.15.0
  flutter_image_compress: ^2.2.0
  path_provider: ^2.1.3
  firebase_remote_config: ^4.4.5
  firebase_analytics: ^10.10.5
  dio_cache_interceptor: ^3.5.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.0.0
  copy_with_extension_gen: ^5.0.4
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.4.0
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.0
  freezed: ^2.5.2
  flutter_lints: ^3.0.2
  injectable_generator: ^2.6.1
  # flutter_dotenv: ^5.0.2


flutter:

  uses-material-design: true
  assets:
    - assets/translations/
    - assets/svg/
    - assets/fonts/
    - assets/icon/
    - assets/env/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Light-BETA.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

#  colors:
#    inputs:
#      - assets/color/colors.xml

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/logo.png"
  adaptive_icon_background: null